### ISSUE TITLE
bug: SleepTime is not correctly cleared in stop method

### ISSUE THREAD

**Issue by matt-d-rat** [timrach/sleeptime#3]
I noticed a typo in your stop function that would result in the timer not being cleared correctly.
On [line 34](https://github.com/timrach/sleeptime/blob/master/lib/sleeptime.js#L34) you call:

```javascript
clearInterval(this.timeer);
```

It should instead be:

```javascript
clearInterval(this.timer);
```

**Comment by goloroden** [comment]
@matt-d-rat Thanks for the hint, I've created a PR for this (see #4).
